name: data-engineering
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.15.3=hb03c661_0
  - aws-c-auth=0.9.1=h194c533_5
  - aws-c-cal=0.9.8=h346e085_0
  - aws-c-common=0.12.5=hb03c661_1
  - aws-c-compression=0.3.1=h7e655bb_8
  - aws-c-event-stream=0.5.6=h1deb5b9_4
  - aws-c-http=0.10.7=had4b759_1
  - aws-c-io=0.23.2=hbff472d_2
  - aws-c-mqtt=0.13.3=h8ba2272_8
  - aws-c-s3=0.8.6=h493c25d_7
  - aws-c-sdkutils=0.2.4=h7e655bb_3
  - aws-checksums=0.2.7=h7e655bb_4
  - aws-crt-cpp=0.35.0=h719b17a_2
  - aws-sdk-cpp=1.11.606=h522d481_6
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - boto3=1.40.13=pyhd8ed1ab_0
  - botocore=1.40.13=pyge39_1234567_0
  - brotli-python=1.1.0=py39hf88036b_3
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=12.3.0=h6083320_0
  - icu=78.2=h33c6efd_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=21.0.0=h91d8edf_10_cpu
  - libarrow-acero=21.0.0=h635bf11_10_cpu
  - libarrow-compute=21.0.0=h8c2c5c3_10_cpu
  - libarrow-dataset=21.0.0=h635bf11_10_cpu
  - libarrow-substrait=21.0.0=h3f74fd7_10_cpu
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.11.0=5_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.86.3=h6548e54_0
  - libgomp=15.2.0=he0feb66_16
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=21.0.0=h7376487_10_cpu
  - libpng=1.6.54=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libutf8proc=2.11.2=hfe17d71_0
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json=3.12.0=h54a6638_1
  - numpy=1.26.4=py39h474f0d3_0
  - openjdk=11.0.29=h777afb3_0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - pandas=2.3.1=py39h1b6b32d_0
  - pcre2=10.47=haa7fec5_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - prometheus-cpp=1.3.0=ha5d0236_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - py4j=0.10.9.7=pyhd8ed1ab_0
  - pyarrow=21.0.0=py39hf3d152e_0
  - pyarrow-core=21.0.0=py39h1aa8787_0_cpu
  - pysocks=1.7.1=pyha55dd90_7
  - pyspark=3.5.0=pyhd8ed1ab_0
  - python=3.9.23=hc30ae73_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=h853b02a_0
  - s2n=1.6.0=h8399546_1
  - s3transfer=0.13.1=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - tk=8.6.13=noxft_ha0e22de_103
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - urllib3=1.26.19=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
  - pip:
    - Jinja2==3.1.6
    - MarkupSafe==3.0.3
    - PyYAML==6.0.3
    - Pygments==2.19.2
    - Send2Trash==2.1.0
    - anyio==4.12.1
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - arrow==1.4.0
    - asttokens==3.0.1
    - async-lru==2.0.5
    - attrs==25.4.0
    - babel==2.17.0
    - beautifulsoup4==4.14.3
    - bleach==6.2.0
    - certifi==2026.1.4
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - comm==0.2.3
    - debugpy==1.8.19
    - decorator==5.2.1
    - defusedxml==0.7.1
    - exceptiongroup==1.3.1
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - fqdn==1.5.1
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - idna==3.11
    - importlib_metadata==8.7.1
    - ipykernel==6.31.0
    - ipython==8.18.1
    - isoduration==20.11.0
    - jedi==0.19.2
    - json5==0.13.0
    - jsonpointer==3.0.0
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter-events==0.12.0
    - jupyter-lsp==2.3.0
    - jupyter_client==8.6.3
    - jupyter_core==5.8.1
    - jupyter_server==2.17.0
    - jupyter_server_terminals==0.5.4
    - jupyterlab==4.5.3
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.28.0
    - kagglehub==0.3.13
    - lark==1.3.1
    - matplotlib-inline==0.2.1
    - mistune==3.2.0
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - notebook==7.5.3
    - notebook_shim==0.2.4
    - overrides==7.7.0
    - packaging==25.0
    - pandocfilters==1.5.1
    - parso==0.8.5
    - pexpect==4.9.0
    - platformdirs==4.4.0
    - prometheus_client==0.24.1
    - prompt_toolkit==3.0.52
    - psutil==7.2.2
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - pycparser==2.23
    - python-json-logger==4.0.0
    - pyzmq==27.1.0
    - referencing==0.36.2
    - requests==2.32.5
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rpds-py==0.27.1
    - soupsieve==2.8.3
    - stack-data==0.6.3
    - terminado==0.18.1
    - tinycss2==1.4.0
    - tomli==2.4.0
    - tornado==6.5.4
    - traitlets==5.14.3
    - typing_extensions==4.15.0
    - uri-template==1.3.0
    - wcwidth==0.5.0
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.9.0
    - zipp==3.23.0

prefix: "/home/neli/.local/share/mamba/envs/data-engineering"
