name: data-engineering
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - pandas=2.3.1
  - matplotlib
  - pyspark=3.5.0
  - pyarrow=21.0.0
  - boto3=1.40.13
  - botocore=1.40.13
  - python-dateutil
  - tqdm
  - requests=2.32.5
  - urllib3
  - jupyterlab
  - ipykernel
  - openjdk=17
  - pip:
      - kagglehub==0.3.13
